version: '3.5'

services:

  db:
    image: mariadb:10.10.2
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./db-dump:/docker-entrypoint-initdb.d
    environment:
      MARIADB_USER: roles-service
      MARIADB_PASSWORD: roles-service-secret
      MARIADB_ROOT_PASSWORD: root-pw
      MARIADB_DATABASE: roles-service
    ports:
      - "3306:3306"
    networks:
      - roles-service-network

  service:
    image: roles-service:latest
    depends_on:
      - db
    environment:
      - spring.datasource.url=jdbc:mariadb://db:3306/roles-service?useSSL=false
    ports:
      - "8080:8080"
    networks:
      - roles-service-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8090:8080"
    networks:
      - roles-service-network

networks:
  roles-service-network: